[destination.filesystem]
bucket_url = "<configure me>" # fill this in!

[destination.filesystem.credentials]
aws_access_key_id = "<configure me>" # fill this in!
aws_secret_access_key = "<configure me>" # fill this in!
